name: Auto Rebase PR flex-pcb-fix on main changes

# Fügen Sie diese Zeilen am Anfang hinzu
permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  rebase-flex-pcb-fix:
    name: Rebase flex-pcb-fix
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Rebase flex-pcb-fix onto main
        run: |
          git checkout flex-pcb-fix
          git rebase main
          git push --force-with-lease origin flex-pcb-fix
